apiVersion: skaffold/v2beta26         # version of the configuration.
kind: Config                          # always Config
deploy:                               # describes how images are deployed.
  kubectl:                            # beta uses a client side kubectl apply to deploy manifests.
    manifests:                        # watches for the changes in yaml files in infra/k8s
      - "./infra/k8s/*.yaml"
build:                                # describes how the images are built
  local:                              # [beta] describes how to do a build on the local docker daemon and optionally push to a repository.
    push: false                       # should images be pushed to a registry
  artifacts:                          # the images you're going to be building.
    - image: hhnguyen255/client       # name of the image to be built.
      context: client                 # the directory containing the artifact's sources.
      docker:                         # [beta] describes an artifact built from a Dockerfile.
        dockerfile: Dockerfile        # Locates the Dockerfile relative to workspace.
      sync:                           # [beta] local files synced to pods instead of triggering an image build when modified.
        manual:                       # manual sync rules indicating the source and destination.
          - src: 'src/**/*.tsx'       #	a glob pattern to match local paths against. Directories should be delimited by / on all platforms.
            dest: .                   # destination path in the container where the files should be synced to.
    - image: hhnguyen255/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: hhnguyen255/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: hhnguyen255/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: hhnguyen255/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: hhnguyen255/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
